project:
  type: website
  output-dir: _site

website:
  title: "Transition to HLC"

  open-graph: true

  site-url: https://github.com/Haywood-Community-College-IERG/hlc/index.html
  repo-url: https://github.com/Haywood-Community-College-IERG/hlc
  repo-actions: [edit, source, issue]
  #issue-url: https://github.com/Haywood-Community-College-IERG/hlc/issues/new/choose

  favicon: /images/favicon.png
  #image: /images/Clyde.png

  back-to-top-navigation: true

  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Timeline"
        href: timeline.qmd

      - text: "HLC Process Steps"
        menu:
        - text: "Step 0. BOT Approval"
          href: steps/0_bot_approval.qmd
        - text: "Step 1. Letter to USED"
          href: steps/1_used_letter.qmd
        - text: "Step 2. HLC Application"
          href: steps/2_hlc_application.qmd
      # - text: "Step 3. HLC Preliminary Peer Review"
      #   href: 3_hlc_preliminary_peer_review.qmd
      # - text: "Step 4. HLC Comprehensive Evaluation"
      #   href: 4_hlc_comprehensive_evaluation.qmd
      # - text: "Step 5. HLC Onsite Visit"
      #   href: 5_hlc_onsite_visit.qmd
      # - text: "Step 6. HLC Institutional Actions Council"
      #   href: 6_hlc_institutional_actions_council.qmd
      # - text: "Step 7. Letter to USED"
      #   href: 7_used_letter.qmd

      - text: "Criteria"
        menu:
          - text: "Criterion 1"
            href: criteria/criterion1.qmd
          - text: "Criterion 2"
            href: criteria/criterion2.qmd
          - text: "Criterion 3"
            href: criteria/criterion3.qmd
          - text: "Criterion 4"
            href: criteria/criterion4.qmd
          - text: "Assumed Practices"
            href: criteria/assumed_practices.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "About"
        href: about.qmd

    right:
      - icon: github
        menu:
          - text: "Source Code"
            href: https://github.com/Haywood-Community-College-IERG/hlc
          - text: "Report a Bug/Suggest a Change"
            href: https://github.com/Haywood-Community-College-IERG/hlc/issues/new/choose

typst:
  title: "Transition to HLC"
  author: "David Onder"
  date: "11/20/2024"

bibliography: references.bib

format:
  html:
    theme: [cosmo, assets/custom_theme.scss]
    toc: true
    smooth-scroll: true
    highlight: arrow
    page-layout: full
  # pdf:
  #   documentclass: scrreprt
  #   toc: true
  #   section-numbering: 1.1.a
  typst:
    toc: true
    section-numbering: 1.1.a

