# Step 2. HLC Application

::: {.callout-important}
About 30 days prior to submitting the application, the college should notify HLC of its intention to apply.
This allows HLC time to setup your college in their system prior to the actual application. 
The college will then be able to transfer the application fee funds[^s2_hlc_dues_and_fees] immediatly following the application.

You can use the [inquiry form](https://www.hlcommission.org/accreditation/begin-your-accreditation-journey/seeking-accreditation-inquiry-form/) {{< fa solid up-right-from-square title="A webpage link icon" >}} to start this conversation or submit a more formal letter of notifiction.
An example letter is provided below.
:::

## The Application and Evidence {#sec-the-application-and-evidence}

As part of the accelerated process[^s2_hlc_accelerated_process] application, colleges need to submit 13 pieces of evidence in addition to the brief application[^s2_hlc_application_link]. You should use the Microsoft Word template provided by HLC to complete the evidence portion of the application. This should be converted to a PDF and submitted with the application. Be sure to include links from an index page to each piece of evidence in the PDF as well as links back to the index page.

Here is a summary of those pieces of evidence with some tips for each:

### 1. Official Communications

*All communications between the institution and its current accreditor from the past 12 months.*

- If the institution has recently completed a Fifth-Year Interim Report, include only the findings letter from SACSCOC when it is received.
- In general, do not include any of the submission materials (Fifth-Year Interim Report, New Program Prospectus, etc.) unless specifically requested. You can include the cover letter included with the submission materials or even the confirmation email from the upload. 
- If no response has been received for one of the institution's submissions prior to submission of the application, include the a note indicating a response is pending.

### 2. Accreditation Documentation {#sec-accreditation-documentation}

*Proof of current institutional accreditation by a USED-recognized accreditor.*

- Include a screenshot from the US Department of Education's Database of Accredited Postsecondary Insittutions and Programs [https://ope.ed.gov/dapip/](https://ope.ed.gov/dapip/).

### 3. Reaffirmation of Accreditation

*Evidence of one reaffirmation of accreditation or other indicators of continuity and stability.*

- The screenshot from \nameref{sec-accreditation-documentation} includes the recent history and the date of first accreditation, which satisfies this evidence as well.

### 4. Sanction Status

*Documentation showing no sanctions or negative actions from the current accreditor for at least five years.*

- The screenshot from \nameref{sec-accreditation-documentation} includes the recent history, including any sanctions or negative actions from SACSCOC.

### 5. USED Approval

*Approval from the USED Federal Student Aid office for changing or maintaining multiple accreditations.*

- Just include a copy of the letter received from the USED Federal Student Aid office.

### 6. Substantial Presence Worksheet 

*Completed worksheet[^s2_hlc_sub_pres_wksht] demonstrating substantial presence within HLC’s jurisdiction.*

The Substantial Presence Worksheet is a document that HLC uses to determine if an institution has a substantial presence in their jurisdiction. This is important because it helps HLC understand the institution's operations and its relationship with the students and communities it serves.


::: {.callout-note collapse=true}
#### For NC Working Group institutions

This is relatively straightforward as the institution is located in NC and serves students in NC. See below for details on each portion.
:::


::: {.callout-note collapse=true}
#### Substantial Presence Worksheet

1. Where is the institution incorporated?

   For state institutions, this is likely answered by referring to state law.

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "The institution is authorized by law to operate in <countyname> County in the state of North Carolina.
   :::

2. In which states, sovereign nations, or other jurisdictions is the institution authorized to offer educational programs?

   List all the locations where the institution is authorized to offer educational programs.

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "North Carolina"
   :::

3. Where is the work of the chief executive officer (CEO) conducted?

   The CEO is the president of the institution. This is typically where the president's office is located.

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "The work of the CEO is typically conducted in person on campus at <collegename> Community College in <collegecity>, NC."
   :::
 
4. Where and through what mechanisms (in-person, virtual meetings, etc.) do the CEO, senior administrators, cabinet, and other administrators conduct their work together, and what is the frequency of these meetings?

   The senior administrators are the vice presidents and other senior leaders of the institution. The cabinet is typically the executive team of the institution. 

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "The senior administrators and cabinet typically meet in person on campus at <collegename> Community College in <collegecity>, NC. The executive team typically meets <frequency> and includes the <executiveteam>. The <leadershipteamname> meets every <frequency> and includes <leadershipteam>."
   :::

5. Where and through what mechanisms (in-person, virtual meetings, etc.) does the governing board conduct its meetings, and what is the frequency of these meetings?

   The governing board is the board of trustees or other governing body of the institution. 

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "The governing board typically meets in person on campus at <collegename> Community College in <collegecity>, NC. The board meets every <frequency>."

   Also include if the meetings are broadcast online or if the board members are able to join the meeting online.
   :::

6. Describe the institution’s general level of workplace centralization, including components of the institution in which faculty, staff and administration work virtually/remotely.  

   This is typically where the institution's faculty, staff, and administration work. 

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "The institution's faculty, staff, and administration work primarily in person on campus at <collegename> Community College in <collegecity>, NC. The institution has a small number of employees who work remotely or virtually. The students commute to campus for classes and services or are enrolled in online programs. <collegename> Community College is not authorized to offer online courses to students outside of North Carolina."
   :::

7. From what locations and through what mechanisms (in-person, online, vendor-provided services, etc.) does the institution receive and process tuition and fee payments?
 
   This is typically where the institution's tuition and fee payments are processed. 

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "The institution receives and processes tuition and fee payments in person on campus at <collegename> Community College in <collegecity>, NC. The institution also accepts online payments through the college's website."

   The response may also include information about third-party payment plans or sponsorship payments.
   :::

8. Where does the institution maintain bank accounts?

   This is typically where the institution's bank accounts are maintained. Be sure to identify all the banks that the institution uses for its accounts.

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "The institution maintains its bank accounts with <bankname> in <bankcity>, NC.""
   :::

9. Where is the work of the chief financial officer (CFO) conducted?

   This is typically where the institution's CFO works. The CFO is typically the vice president of finance or business affairs.

   ::: {.callout-note collapse=true}
   #### For NC Working Group institutions

   An acceptable answer would be: "The work of the CFO is typically conducted in person on campus at <collegename> Community College in <collegecity>, NC."
   :::
 
10. Where are customer service representatives and enrollment management personnel located when responding to inquiries from students or the public?
    
    This is typically where the institution's customer service representatives and enrollment management personnel work. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution's customer service representatives and enrollment management personnel are typically located in person on campus at <collegename> Community College in <collegecity>, NC. The institution also has a small number of employees who work remotely or virtually as needed or on occasion."
    :::
 
11. What is the address of record for IRS filings (e.g., tax statements, 990s, etc.)?

    This is main address of the institution used on IRS filings. 

12. In what state(s) or countries does the institution file tax-related documents? 

    This is typically where the institution files its tax-related documents. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution files its tax-related documents in North Carolina."
    :::

13. Who provides the institution’s human resource function, and from where does this work occur?

    This is typically where the institution's human resource function is provided. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution's human resource function is provided by the Human Resources department, which is located in person on campus at <collegename> Community College in <collegecity>, NC."
    :::

14. Where is the work of the chief information officer conducted? If hardware is used to support the educational enterprise (including, if applicable, servers supporting online delivery), where is it located and from where is it supported?

    This is typically where the institution's chief information officer works. The chief information officer is typically the vice president of information technology or information services.

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The work of the chief information officer is typically conducted in person on campus at <collegename> Community College in <collegecity>, NC. The institution's IT department is located on campus and provides support for all hardware used to support the educational enterprise."
    :::
 
15. Where is the work of educational administration employees (e.g., vice president for academic affairs/Provost, deans, etc.) conducted? 

    This is typically where the institution's educational administration employees work. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The work of educational administration employees is typically conducted in person on campus at <collegename> Community College in <collegecity>, NC."
    :::
 
16. Who is involved in curriculum development and program review, and from where is this work accomplished? 

    This is typically where the institution's curriculum development and program review work is accomplished. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution's curriculum development and program review work is accomplished by the faculty and academic administration, which is typically conducted in person on campus at <collegename> Community College in <collegecity>, NC."
    :::
 
17. Who maintains student records for the institution, including the role of registrar, and from where does this work occur?

    This is typically where the institution's student records are maintained. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution's student records are maintained by the registrar's office, which is typically located in person on campus at <collegename> Community College in <collegecity>, NC."
    :::

18. From where are student support services (e.g., advisors, career counselors, student affairs professionals) provided?

    This is typically where the institution's student support services are provided. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution's student support services are provided in person on campus at <collegename> Community College in <collegecity>, NC. The institution has a small number of employees who work remotely or virtually as needed or on occasion."
    :::
 
19. List all campuses and additional locations, and identify the main campus. Include the name(s) of the location, if any, and the address(es). If the institution does not have a main campus, list the name and address of the institutional headquarters.

    This is where the institution's campuses and additional locations are located. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution's main campus is located at <collegeaddress> in <collegecity>, NC. The institution has no additional locations."
    :::
 
20. Describe the geographic location(s) in which the institution markets its programs and from where it derives its aggregate enrollments, including both on-ground and on-line instructional modalities.  Include data that differentiates between what occurs within HLC’s jurisdiction and what occurs outside of HLC’s jurisdiction.

    This is where the institution's programs are marketed and where its enrollments are derived. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution markets its programs primarily in North Carolina, specifically in <countyname> County. The institution does not market its programs outside of North Carolina and generally does not market its programs outside of its assigned service area. The institution's aggregate enrollments are primarily derived from students in <countyname> County and the surrounding counties."
    :::

21. Describe any vendor relationships, outsourcing, or shared services arrangements that support instruction, faculty development, academic advising, library and information expertise and resources, career placement, student support services, assessment, program development and review, and institutional research.  From where are these activities managed and supported?  

    This is where the institution's vendor relationships and outsourcing arrangements are located. 

    ::: {.callout-note collapse=true}
    #### For NC Working Group institutions

    An acceptable answer would be: "The institution has a number of vendor relationships and outsourcing arrangements that <examples>. These activities are typically managed and supported in person on campus at <collegename> Community College in <collegecity>, NC."
    :::

:::

### 7. Incorporation Documentation

*Proof of incorporation or operation under federal authority within HLC’s jurisdiction.*

This will depend on how the institution is organized and operates. State institutions are likely governed by state law and may not have a formal incorporation document. Refer to the statutes to establish the legal foundation of the institution.

::: {.callout-note collapse=true}
#### For NC Working Group institutions

Make reference to NC General Statutes 115D-5 which authorizes the State Board to regulate all aspects of community college operations, including the approval of curricula and the awarding of degrees, diplomas, and certificates.

Then reference NCCCS State Board Code Section 1A SBCCC 300.1 which provides definitions that establish the framework for community college governance, including the definition of “service area”.

Finally, reference NCCCS State Board Code Section 1A SBCCC 300.3 which defines the specific service areas for each community college in North Carolina.
:::

### 8. Degree Authorization

*Legal authorization to award degrees in at least one state or jurisdiction within HLC’s area.*

Similarly to \nameref{sec-incorporation-documentation} above, public institutions are likely governed by state law and may not have a formal incorporation document. Refer to the statutes to establish the authorization to award degrees.

::: {.callout-note collapse=true}
#### For NC Working Group institutions

Make reference to NCCCS State Board Code Section 1D SBCCC 400.6 which outlines the process by which the State Board approves degree, diploma, and certificate programs.
:::

### 9. Educational Programs List {#sec-educational-programs-list}

*List of all educational programs offered, including those by distance or correspondence education.*

- Should include all programs offered by the institution at a particular point in time. 
- Include the time frame for the list, such as "All active programs for AY 2024-2025".
- Can combine with \nameref{sec-enrollment-information} to provide a comprehensive view of the institution's educational offerings.
- Also include the mode of delivery (e.g., in-person, online, correspondence) and the location (campus) of each program.

### 10. Enrollment Information 

*Current enrollments in all educational programs by program, location, and mode of delivery.*

- This can be included with the full list of programs under \nameref{sec-educational-programs-list}.

### 11. Accreditor Relationships

*Inventory of relationships with other recognized accreditors, including any sanctions or adverse actions.*

- These should be reflective of accreditors and state authorizing agencies that have accredited or approved the institution's programs.
- For NC community colleges, this includes the NC Board of Nursing. It does not include BLET or EMS programs if they are housed within continuing education.
- This is just a list of these relationships and does not include any documentation. It should include the name of the program, the accreditor, and the date of the last review or action, and the current standing.
- You may consider including documentation for any adverse actions or sanctions.

### 12. Governing Board Authorization

*Documentation indicating the governing board’s authorization to seek accreditation with HLC.*

- Here are some sample board presentation outlines:
    - **Haywood Community College**
        - Board was presented their discussion and motion from previous year where the institution decided to submit an application to USED for permission to apply to HLC.
        - Board was shown letter from USED granting approval to proceed with applying to HLC.
            - [2025-03-20 USED Approval Letter](documents/2025-03-20 USED - Approval for Haywood Community College 00808300.pdf)
        - Board made a motion directing the president or her designee to apply for accreditation with HLC.
        - Board was shown letters to both SACSCOC and NCCCS declaring our intentions for their information.
            - [2025-05-07 SACSCOC Notification Letter](documents/2025-05-07 HCC - SACSCOC Notification Letter.pdf)
            - [2025-05-07 NCCCS Notification Letter](documents/2025-05-07 HCC - NCCCS Notification Letter.pdf)
        - NOTE: Letters were sent the day after the board meeting and HLC was notified of the intent to apply via the [HLC Inquiry Form](https://www.hlcommission.org/accreditation/begin-your-accreditation-journey/seeking-accreditation-inquiry-form/).

## Other Resources

See [Resources](..\resources.qmd) for more details.

- Seeking Accreditation Workshop handout

## Other topics of interest

- Learn about the responsibilities of the Accreditation Liaison Office[^s2_hlc_alo]

## Actual Sample Applications

### Haywood Community College

- [2025-05-30 Application with Evidence](../documents/2025-05-30 HCC - Haywood CC Application with Evidence.pdf)
- [2025-06-20 Application Acceptance Letter](../documents/2025-06-20 HLC - Application Acceptance Letter.pdf)

## Resources

- [HLC Application Link](https://www.hlcommission.org/accreditation/begin-your-accreditation-journey/application-for-hlc-membership/) {{< fa solid up-right-from-square title="A webpage link" >}}
- [HLC Inquiry Form](https://www.hlcommission.org/accreditation/begin-your-accreditation-journey/seeking-accreditation-inquiry-form/) {{< fa solid up-right-from-square title="A webpage link" >}}
- [HLC Accelerated Process for Initial Accreditation](https://download.hlcommission.org/seeking-accreditation/AcceleratedInitialAccreditation_PRC.pdf) {{< fa solid file-pdf title="A PDF document" >}}
- [HLC Dues and Fees Schedule](https://www.hlcommission.org/accreditation/dues-and-fees-schedule/) {{< fa solid up-right-from-square title="A webpage link icon" >}}
- [HLC Accreditation Liaison Office role and responsibility](https://www.hlcommission.org/accreditation/accreditation-roles-on-campus/#alo) {{< fa solid up-right-from-square title="A webpage link icon" >}}
- [HLC Substantial Presence Worksheet](https://download.hlcommission.org/seeking-accreditation/SubstantialPresence_FRM.docx) {{< fa solid file-word title="A Word document icon" >}}

::: {.callout-note appearance="simple"}
## Icon Reference

- {{< fa solid file-excel title="An Excel document icon" >}} - Excel document 
- {{< fa solid up-right-from-square title="A webpage link icon" >}} - Webpage link 
- {{< fa solid file-pdf title="A PDF document icon" >}} - PDF document 
- {{< fa solid folder-tree title="A policy link or document icon" >}} - Policy link or document
- {{< fa solid video title="A video link icon" >}} - Video link
- {{< fa solid file-word title="A Word document icon" >}} - Word document
:::

[^s2_hlc_application_link]: [HLC Application Link](https://www.hlcommission.org/accreditation/begin-your-accreditation-journey/application-for-hlc-membership/) {{< fa solid up-right-from-square title="A webpage link" >}}
[^s2_hlc_accelerated_process]: [HLC Accelerated Process for Initial Accreditation](https://download.hlcommission.org/seeking-accreditation/AcceleratedInitialAccreditation_PRC.pdf) {{< fa solid file-pdf title="A PDF document" >}}
[^s2_hlc_dues_and_fees]: [HLC Dues and Fees Schedule](https://www.hlcommission.org/accreditation/dues-and-fees-schedule/) {{< fa solid up-right-from-square title="A webpage link icon" >}}
[^s2_hlc_alo]: [HLC Accreditation Liaison Office role and responsibility](https://www.hlcommission.org/accreditation/accreditation-roles-on-campus/#alo) {{< fa solid up-right-from-square title="A webpage link icon" >}}
[^s2_hlc_sub_pres_wksht]: [HLC Substantial Presence Worksheet](https://download.hlcommission.org/seeking-accreditation/SubstantialPresence_FRM.docx) {{< fa solid file-word title="A Word document icon" >}}

## Updates:

### 2025-05-13

- Revised the list of evidence to remove the "Voluntary Decision Explanation" (formerly Evidence 6) as it is no longer needed.
